[menu __main filament_lanes]
name: Filament
icon: filament
panel: filament_lanes

[menu __main qbox]
name: QiDi Box
icon: logo_qidi_white

[menu __main qbox remove_0]
name: Remove 0
icon: arrow-up
method: printer.gcode.script
params: {"script":"E_BOX SLOT=0"}

[menu __main qbox remove_1]
name: Remove 1
icon: arrow-up
method: printer.gcode.script
params: {"script":"E_BOX SLOT=1"}

[menu __main qbox remove_2]
name: Remove 2
icon: arrow-up
method: printer.gcode.script
params: {"script":"E_BOX SLOT=2"}

[menu __main qbox remove_3]
name: Remove 3
icon: arrow-up
method: printer.gcode.script
params: {"script":"E_BOX SLOT=3"}

[menu __main qbox reload_0]
name: Reload 0
icon: refresh
method: printer.gcode.script
params: {"script":"RFID_READ SLOT=slot0"}

[menu __main qbox reload_1]
name: Reload 1
icon: refresh
method: printer.gcode.script
params: {"script":"RFID_READ SLOT=slot1"}

[menu __main qbox reload_2]
name: Reload 2
icon: refresh
method: printer.gcode.script
params: {"script":"RFID_READ SLOT=slot2"}

[menu __main qbox reload_3]
name: Reload 3
icon: refresh
method: printer.gcode.script
params: {"script":"RFID_READ SLOT=slot3"}

[menu __print qbox]
name: QiDi Box
icon: logo_qidi_white

[menu __print qbox remove_0]
name: Remove 0
icon: arrow-up
method: printer.gcode.script
params: {"script":"E_BOX SLOT=0"}

[menu __print qbox remove_1]
name: Remove 1
icon: arrow-up
method: printer.gcode.script
params: {"script":"E_BOX SLOT=1"}

[menu __print qbox remove_2]
name: Remove 2
icon: arrow-up
method: printer.gcode.script
params: {"script":"E_BOX SLOT=2"}

[menu __print qbox remove_3]
name: Remove 3
icon: arrow-up
method: printer.gcode.script
params: {"script":"E_BOX SLOT=3"}

[menu __print qbox reload_0]
name: Reload 0
icon: refresh
method: printer.gcode.script
params: {"script":"RFID_READ SLOT=slot0"}

[menu __print qbox reload_1]
name: Reload 1
icon: refresh
method: printer.gcode.script
params: {"script":"RFID_READ SLOT=slot1"}

[menu __print qbox reload_2]
name: Reload 2
icon: refresh
method: printer.gcode.script
params: {"script":"RFID_READ SLOT=slot2"}

[menu __print qbox reload_3]
name: Reload 3
icon: refresh
method: printer.gcode.script
params: {"script":"RFID_READ SLOT=slot3"}

#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# 24htime = False
#~# font_size = large
#~# print_sort_dir = date_desc
#~#
